import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider, SideBar, NavBar } from "@/components"
const inter = Inter({ subsets: ["latin"] });
import { ToastContainer, toast } from 'react-toastify';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
             <NavBar />   
            <div className="">
           
            <ToastContainer />
              <body className={`${inter.className} p-8 pl-32`}>
                {children}
              </body>
            </div>
      </ThemeProvider>
    </html>
  );
}
